site_name: MiniMC
theme: material
plugins:
  - macros
nav:
  - 'Introduction': index.md
  - 'Configurable Program Analysis':
      - 'CPA': cpa/index.md
      - 'Location CPA': cpa/location.md
      - 'Explicit Value CPA': cpa/explicit.md
      - 'Path formula CPA': cpa/symbolic.md
extra:
  minimc: MiniMC
markdown_extensions:
  - admonition
