name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
    - uses: actions/checkout@v2
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libtinfo-dev zlib1g-dev git g++-12 cmake libboost-dev libboost-program-options-dev cvc4 libcvc4-dev libcln-dev zip flex bison
        version: 1.0
    - name: build
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=g++-12 -DCMAKE_BUILD_TYPE=Release --build .. --target minimc
    - name: test
      run: cd build && ctest --output-on-failure
    - name: package
      run: cd build && make package
    - uses: actions/upload-artifact@v2
      with:
        name: build 
        path: build/*.zip 
